# 路径配置  
paths:  
  main_data_path: "/home/qyl/CSD_data/1_CSD/DATA_clean/output_deduped2.xlsx"  
  checkpoint_dir: "/home/qyl/CSD_data/1_CSD/logs/gener/visualizations_5.9_4.15_plus"  
  visualization_dir: "/home/qyl/CSD_data/1_CSD/logs/gener/visualizations_5.9_4.15_plus"  
  output_path: "/home/qyl/CSD_data/1_CSD/logs/gener/visualizations_5.9_4.15_plus/generated_molecules_vae_final3.xlsx"  
  generate_path: "/home/qyl/CSD_data/1_CSD/logs/gener/visualizations_5.9_4.15_plus/generated_molecules3.xlsx"  
  output_dir: "/home/qyl/CSD_data/1_CSD/logs/gener/visualizations_5.9_4.15_plus"
  val_data_path: "/home/qyl/CSD_data/1_CSD/logs/gener/visualizations_5.9_4.15_plus/val_ft_data.csv"
  ft_data_path: "/home/qyl/CSD_data/1_CSD/logs/gener/visualizations_5.9_4.15_plus/ft_data.csv"
  metal_properties_sheet: "metal"
  solvent_properties_sheet: "sol_pro4"
  pca_model_path: "/home/qyl/CSD_data/1_CSD/logs/ensemble/4.10____4/sol_min4_FF60_5.pkl"
  model_checkpoints_path: "/home/qyl/CSD_data/1_CSD/logs/ensemble/4.10____4/iterations/checkpoints"


# 数据配置  
data:  
  main_sheet: "sol_min5"  
  ft_sheet: "logd_all3"
  metal_sheet: "metal"
  smiles_column: "SMILES"
  metal_column: "Metal"  
  max_len: 100  
  augment_prob: 0.5  
  val_ratio: 0.1  
  test_ratio: 0.1  

# 模型配置  
model:  
  latent_dim: 128  
  embedding_dim: 256  
  hidden_dim: 512  
  num_layers: 4  
  dropout: 0.5


# 训练配置  
training:  
  device: "cuda:0"  # Remove the Python conditional - handle this in code instead  
  batch_size: 32  
  num_workers: 4
  vae_lr: 0.005
  gamma: 0.99  # 折扣因子
  alpha: 0.6   # 优先级采样指数
  beta: 0.4    # 重要性采样指数 
  value_lr: 0.05  

  # 主训练参数  
  main_epochs: 300  
  main_lr: 0.001  
  beta_start: 0.0  
  beta_end: 0.5  
  warmup_epochs: 20  

  # 微调参数  
  ft_epochs: 100  
  ft_lr: 0.0008  
  ft_beta: 0.3  
  ft_batch: 16  
  partial_unfreeze: true
  save_ft_data: true  

  # 加载模型  
  load_pre_model: true
  policy_lr: 0.005  

# 生成配置  
generation:  
  num_samples: 2000  
  temperature: 0.7  
  nucleus_p: 0.92  
  perturb_scale: 0.2  
  similarity_threshold: 0.4
  top_k: 20

visualization:
  img_size: 300  # 图片尺寸
  mols_per_row: 5  # 每行显示分子数
  radar_properties: ['MolWt', 'NumHAcceptors', 'NumHDonors', 'MolLogP', 'RingCount']  # 雷达图属性

molecule_workflow:
  novelty_weight: 1.2
  diversity_weight: 0.8
  similarity_threshold: 0.6